
if (FILE AND SRC)
  set(TEXT_PREFIX "# Do not edit this file, rather use:")
  if (APPLE)
    set(DIR_HINT "HOME/Library/Application Support/data/xca/${FILE}.txt")
  elseif (WIN32)
    set(DIR_HINT "PROFILE\\Application Data\\xca\\${FILE}.txt")
  else()
    set(DIR_HINT "/usr/local/share/xca/${FILE}.txt or HOME/.local/share/xca/${FILE}.txt")
  endif()

  file(READ "${SRC}/misc/${FILE}.text" CONT)
  file(WRITE "misc/${FILE}.txt"
		${TEXT_PREFIX} "\n# "
		${DIR_HINT} "\n"
		${CONT})
else()
  message(FATAL_ERROR "Mandatory FILE or SRC variable not defined")
endif()

